package com.sitech.cbn.cust.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BsBulidinglistInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_bulidinglist_info
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_bulidinglist_info
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_bulidinglist_info
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_bulidinglist_info
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public BsBulidinglistInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_bulidinglist_info
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_bulidinglist_info
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_bulidinglist_info
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_bulidinglist_info
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_bulidinglist_info
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_bulidinglist_info
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_bulidinglist_info
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_bulidinglist_info
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_bulidinglist_info
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_bulidinglist_info
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_bulidinglist_info
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBuildingNoIsNull() {
            addCriterion("BUILDING_NO is null");
            return (Criteria) this;
        }

        public Criteria andBuildingNoIsNotNull() {
            addCriterion("BUILDING_NO is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingNoEqualTo(Long value) {
            addCriterion("BUILDING_NO =", value, "buildingNo");
            return (Criteria) this;
        }

        public Criteria andBuildingNoNotEqualTo(Long value) {
            addCriterion("BUILDING_NO <>", value, "buildingNo");
            return (Criteria) this;
        }

        public Criteria andBuildingNoGreaterThan(Long value) {
            addCriterion("BUILDING_NO >", value, "buildingNo");
            return (Criteria) this;
        }

        public Criteria andBuildingNoGreaterThanOrEqualTo(Long value) {
            addCriterion("BUILDING_NO >=", value, "buildingNo");
            return (Criteria) this;
        }

        public Criteria andBuildingNoLessThan(Long value) {
            addCriterion("BUILDING_NO <", value, "buildingNo");
            return (Criteria) this;
        }

        public Criteria andBuildingNoLessThanOrEqualTo(Long value) {
            addCriterion("BUILDING_NO <=", value, "buildingNo");
            return (Criteria) this;
        }

        public Criteria andBuildingNoIn(List<Long> values) {
            addCriterion("BUILDING_NO in", values, "buildingNo");
            return (Criteria) this;
        }

        public Criteria andBuildingNoNotIn(List<Long> values) {
            addCriterion("BUILDING_NO not in", values, "buildingNo");
            return (Criteria) this;
        }

        public Criteria andBuildingNoBetween(Long value1, Long value2) {
            addCriterion("BUILDING_NO between", value1, value2, "buildingNo");
            return (Criteria) this;
        }

        public Criteria andBuildingNoNotBetween(Long value1, Long value2) {
            addCriterion("BUILDING_NO not between", value1, value2, "buildingNo");
            return (Criteria) this;
        }

        public Criteria andTenancyCodeIsNull() {
            addCriterion("TENANCY_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTenancyCodeIsNotNull() {
            addCriterion("TENANCY_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTenancyCodeEqualTo(String value) {
            addCriterion("TENANCY_CODE =", value, "tenancyCode");
            return (Criteria) this;
        }

        public Criteria andTenancyCodeNotEqualTo(String value) {
            addCriterion("TENANCY_CODE <>", value, "tenancyCode");
            return (Criteria) this;
        }

        public Criteria andTenancyCodeGreaterThan(String value) {
            addCriterion("TENANCY_CODE >", value, "tenancyCode");
            return (Criteria) this;
        }

        public Criteria andTenancyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TENANCY_CODE >=", value, "tenancyCode");
            return (Criteria) this;
        }

        public Criteria andTenancyCodeLessThan(String value) {
            addCriterion("TENANCY_CODE <", value, "tenancyCode");
            return (Criteria) this;
        }

        public Criteria andTenancyCodeLessThanOrEqualTo(String value) {
            addCriterion("TENANCY_CODE <=", value, "tenancyCode");
            return (Criteria) this;
        }

        public Criteria andTenancyCodeLike(String value) {
            addCriterion("TENANCY_CODE like", value, "tenancyCode");
            return (Criteria) this;
        }

        public Criteria andTenancyCodeNotLike(String value) {
            addCriterion("TENANCY_CODE not like", value, "tenancyCode");
            return (Criteria) this;
        }

        public Criteria andTenancyCodeIn(List<String> values) {
            addCriterion("TENANCY_CODE in", values, "tenancyCode");
            return (Criteria) this;
        }

        public Criteria andTenancyCodeNotIn(List<String> values) {
            addCriterion("TENANCY_CODE not in", values, "tenancyCode");
            return (Criteria) this;
        }

        public Criteria andTenancyCodeBetween(String value1, String value2) {
            addCriterion("TENANCY_CODE between", value1, value2, "tenancyCode");
            return (Criteria) this;
        }

        public Criteria andTenancyCodeNotBetween(String value1, String value2) {
            addCriterion("TENANCY_CODE not between", value1, value2, "tenancyCode");
            return (Criteria) this;
        }

        public Criteria andBuildingNameIsNull() {
            addCriterion("BUILDING_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBuildingNameIsNotNull() {
            addCriterion("BUILDING_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingNameEqualTo(String value) {
            addCriterion("BUILDING_NAME =", value, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameNotEqualTo(String value) {
            addCriterion("BUILDING_NAME <>", value, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameGreaterThan(String value) {
            addCriterion("BUILDING_NAME >", value, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameGreaterThanOrEqualTo(String value) {
            addCriterion("BUILDING_NAME >=", value, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameLessThan(String value) {
            addCriterion("BUILDING_NAME <", value, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameLessThanOrEqualTo(String value) {
            addCriterion("BUILDING_NAME <=", value, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameLike(String value) {
            addCriterion("BUILDING_NAME like", value, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameNotLike(String value) {
            addCriterion("BUILDING_NAME not like", value, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameIn(List<String> values) {
            addCriterion("BUILDING_NAME in", values, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameNotIn(List<String> values) {
            addCriterion("BUILDING_NAME not in", values, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameBetween(String value1, String value2) {
            addCriterion("BUILDING_NAME between", value1, value2, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameNotBetween(String value1, String value2) {
            addCriterion("BUILDING_NAME not between", value1, value2, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingAddrIsNull() {
            addCriterion("BUILDING_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andBuildingAddrIsNotNull() {
            addCriterion("BUILDING_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingAddrEqualTo(String value) {
            addCriterion("BUILDING_ADDR =", value, "buildingAddr");
            return (Criteria) this;
        }

        public Criteria andBuildingAddrNotEqualTo(String value) {
            addCriterion("BUILDING_ADDR <>", value, "buildingAddr");
            return (Criteria) this;
        }

        public Criteria andBuildingAddrGreaterThan(String value) {
            addCriterion("BUILDING_ADDR >", value, "buildingAddr");
            return (Criteria) this;
        }

        public Criteria andBuildingAddrGreaterThanOrEqualTo(String value) {
            addCriterion("BUILDING_ADDR >=", value, "buildingAddr");
            return (Criteria) this;
        }

        public Criteria andBuildingAddrLessThan(String value) {
            addCriterion("BUILDING_ADDR <", value, "buildingAddr");
            return (Criteria) this;
        }

        public Criteria andBuildingAddrLessThanOrEqualTo(String value) {
            addCriterion("BUILDING_ADDR <=", value, "buildingAddr");
            return (Criteria) this;
        }

        public Criteria andBuildingAddrLike(String value) {
            addCriterion("BUILDING_ADDR like", value, "buildingAddr");
            return (Criteria) this;
        }

        public Criteria andBuildingAddrNotLike(String value) {
            addCriterion("BUILDING_ADDR not like", value, "buildingAddr");
            return (Criteria) this;
        }

        public Criteria andBuildingAddrIn(List<String> values) {
            addCriterion("BUILDING_ADDR in", values, "buildingAddr");
            return (Criteria) this;
        }

        public Criteria andBuildingAddrNotIn(List<String> values) {
            addCriterion("BUILDING_ADDR not in", values, "buildingAddr");
            return (Criteria) this;
        }

        public Criteria andBuildingAddrBetween(String value1, String value2) {
            addCriterion("BUILDING_ADDR between", value1, value2, "buildingAddr");
            return (Criteria) this;
        }

        public Criteria andBuildingAddrNotBetween(String value1, String value2) {
            addCriterion("BUILDING_ADDR not between", value1, value2, "buildingAddr");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentIsNull() {
            addCriterion("BUILDING_AGENT is null");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentIsNotNull() {
            addCriterion("BUILDING_AGENT is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentEqualTo(String value) {
            addCriterion("BUILDING_AGENT =", value, "buildingAgent");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentNotEqualTo(String value) {
            addCriterion("BUILDING_AGENT <>", value, "buildingAgent");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentGreaterThan(String value) {
            addCriterion("BUILDING_AGENT >", value, "buildingAgent");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentGreaterThanOrEqualTo(String value) {
            addCriterion("BUILDING_AGENT >=", value, "buildingAgent");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentLessThan(String value) {
            addCriterion("BUILDING_AGENT <", value, "buildingAgent");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentLessThanOrEqualTo(String value) {
            addCriterion("BUILDING_AGENT <=", value, "buildingAgent");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentLike(String value) {
            addCriterion("BUILDING_AGENT like", value, "buildingAgent");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentNotLike(String value) {
            addCriterion("BUILDING_AGENT not like", value, "buildingAgent");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentIn(List<String> values) {
            addCriterion("BUILDING_AGENT in", values, "buildingAgent");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentNotIn(List<String> values) {
            addCriterion("BUILDING_AGENT not in", values, "buildingAgent");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentBetween(String value1, String value2) {
            addCriterion("BUILDING_AGENT between", value1, value2, "buildingAgent");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentNotBetween(String value1, String value2) {
            addCriterion("BUILDING_AGENT not between", value1, value2, "buildingAgent");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentnameIsNull() {
            addCriterion("Building_AgentName is null");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentnameIsNotNull() {
            addCriterion("Building_AgentName is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentnameEqualTo(String value) {
            addCriterion("Building_AgentName =", value, "buildingAgentname");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentnameNotEqualTo(String value) {
            addCriterion("Building_AgentName <>", value, "buildingAgentname");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentnameGreaterThan(String value) {
            addCriterion("Building_AgentName >", value, "buildingAgentname");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentnameGreaterThanOrEqualTo(String value) {
            addCriterion("Building_AgentName >=", value, "buildingAgentname");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentnameLessThan(String value) {
            addCriterion("Building_AgentName <", value, "buildingAgentname");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentnameLessThanOrEqualTo(String value) {
            addCriterion("Building_AgentName <=", value, "buildingAgentname");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentnameLike(String value) {
            addCriterion("Building_AgentName like", value, "buildingAgentname");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentnameNotLike(String value) {
            addCriterion("Building_AgentName not like", value, "buildingAgentname");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentnameIn(List<String> values) {
            addCriterion("Building_AgentName in", values, "buildingAgentname");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentnameNotIn(List<String> values) {
            addCriterion("Building_AgentName not in", values, "buildingAgentname");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentnameBetween(String value1, String value2) {
            addCriterion("Building_AgentName between", value1, value2, "buildingAgentname");
            return (Criteria) this;
        }

        public Criteria andBuildingAgentnameNotBetween(String value1, String value2) {
            addCriterion("Building_AgentName not between", value1, value2, "buildingAgentname");
            return (Criteria) this;
        }

        public Criteria andAmIdIsNull() {
            addCriterion("AM_ID is null");
            return (Criteria) this;
        }

        public Criteria andAmIdIsNotNull() {
            addCriterion("AM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAmIdEqualTo(String value) {
            addCriterion("AM_ID =", value, "amId");
            return (Criteria) this;
        }

        public Criteria andAmIdNotEqualTo(String value) {
            addCriterion("AM_ID <>", value, "amId");
            return (Criteria) this;
        }

        public Criteria andAmIdGreaterThan(String value) {
            addCriterion("AM_ID >", value, "amId");
            return (Criteria) this;
        }

        public Criteria andAmIdGreaterThanOrEqualTo(String value) {
            addCriterion("AM_ID >=", value, "amId");
            return (Criteria) this;
        }

        public Criteria andAmIdLessThan(String value) {
            addCriterion("AM_ID <", value, "amId");
            return (Criteria) this;
        }

        public Criteria andAmIdLessThanOrEqualTo(String value) {
            addCriterion("AM_ID <=", value, "amId");
            return (Criteria) this;
        }

        public Criteria andAmIdLike(String value) {
            addCriterion("AM_ID like", value, "amId");
            return (Criteria) this;
        }

        public Criteria andAmIdNotLike(String value) {
            addCriterion("AM_ID not like", value, "amId");
            return (Criteria) this;
        }

        public Criteria andAmIdIn(List<String> values) {
            addCriterion("AM_ID in", values, "amId");
            return (Criteria) this;
        }

        public Criteria andAmIdNotIn(List<String> values) {
            addCriterion("AM_ID not in", values, "amId");
            return (Criteria) this;
        }

        public Criteria andAmIdBetween(String value1, String value2) {
            addCriterion("AM_ID between", value1, value2, "amId");
            return (Criteria) this;
        }

        public Criteria andAmIdNotBetween(String value1, String value2) {
            addCriterion("AM_ID not between", value1, value2, "amId");
            return (Criteria) this;
        }

        public Criteria andOpDateIsNull() {
            addCriterion("OP_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOpDateIsNotNull() {
            addCriterion("OP_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOpDateEqualTo(Date value) {
            addCriterion("OP_DATE =", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateNotEqualTo(Date value) {
            addCriterion("OP_DATE <>", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateGreaterThan(Date value) {
            addCriterion("OP_DATE >", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateGreaterThanOrEqualTo(Date value) {
            addCriterion("OP_DATE >=", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateLessThan(Date value) {
            addCriterion("OP_DATE <", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateLessThanOrEqualTo(Date value) {
            addCriterion("OP_DATE <=", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateIn(List<Date> values) {
            addCriterion("OP_DATE in", values, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateNotIn(List<Date> values) {
            addCriterion("OP_DATE not in", values, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateBetween(Date value1, Date value2) {
            addCriterion("OP_DATE between", value1, value2, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateNotBetween(Date value1, Date value2) {
            addCriterion("OP_DATE not between", value1, value2, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpOptidIsNull() {
            addCriterion("OP_OPTID is null");
            return (Criteria) this;
        }

        public Criteria andOpOptidIsNotNull() {
            addCriterion("OP_OPTID is not null");
            return (Criteria) this;
        }

        public Criteria andOpOptidEqualTo(String value) {
            addCriterion("OP_OPTID =", value, "opOptid");
            return (Criteria) this;
        }

        public Criteria andOpOptidNotEqualTo(String value) {
            addCriterion("OP_OPTID <>", value, "opOptid");
            return (Criteria) this;
        }

        public Criteria andOpOptidGreaterThan(String value) {
            addCriterion("OP_OPTID >", value, "opOptid");
            return (Criteria) this;
        }

        public Criteria andOpOptidGreaterThanOrEqualTo(String value) {
            addCriterion("OP_OPTID >=", value, "opOptid");
            return (Criteria) this;
        }

        public Criteria andOpOptidLessThan(String value) {
            addCriterion("OP_OPTID <", value, "opOptid");
            return (Criteria) this;
        }

        public Criteria andOpOptidLessThanOrEqualTo(String value) {
            addCriterion("OP_OPTID <=", value, "opOptid");
            return (Criteria) this;
        }

        public Criteria andOpOptidLike(String value) {
            addCriterion("OP_OPTID like", value, "opOptid");
            return (Criteria) this;
        }

        public Criteria andOpOptidNotLike(String value) {
            addCriterion("OP_OPTID not like", value, "opOptid");
            return (Criteria) this;
        }

        public Criteria andOpOptidIn(List<String> values) {
            addCriterion("OP_OPTID in", values, "opOptid");
            return (Criteria) this;
        }

        public Criteria andOpOptidNotIn(List<String> values) {
            addCriterion("OP_OPTID not in", values, "opOptid");
            return (Criteria) this;
        }

        public Criteria andOpOptidBetween(String value1, String value2) {
            addCriterion("OP_OPTID between", value1, value2, "opOptid");
            return (Criteria) this;
        }

        public Criteria andOpOptidNotBetween(String value1, String value2) {
            addCriterion("OP_OPTID not between", value1, value2, "opOptid");
            return (Criteria) this;
        }

        public Criteria andCreateOptidIsNull() {
            addCriterion("CREATE_OPTID is null");
            return (Criteria) this;
        }

        public Criteria andCreateOptidIsNotNull() {
            addCriterion("CREATE_OPTID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateOptidEqualTo(String value) {
            addCriterion("CREATE_OPTID =", value, "createOptid");
            return (Criteria) this;
        }

        public Criteria andCreateOptidNotEqualTo(String value) {
            addCriterion("CREATE_OPTID <>", value, "createOptid");
            return (Criteria) this;
        }

        public Criteria andCreateOptidGreaterThan(String value) {
            addCriterion("CREATE_OPTID >", value, "createOptid");
            return (Criteria) this;
        }

        public Criteria andCreateOptidGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_OPTID >=", value, "createOptid");
            return (Criteria) this;
        }

        public Criteria andCreateOptidLessThan(String value) {
            addCriterion("CREATE_OPTID <", value, "createOptid");
            return (Criteria) this;
        }

        public Criteria andCreateOptidLessThanOrEqualTo(String value) {
            addCriterion("CREATE_OPTID <=", value, "createOptid");
            return (Criteria) this;
        }

        public Criteria andCreateOptidLike(String value) {
            addCriterion("CREATE_OPTID like", value, "createOptid");
            return (Criteria) this;
        }

        public Criteria andCreateOptidNotLike(String value) {
            addCriterion("CREATE_OPTID not like", value, "createOptid");
            return (Criteria) this;
        }

        public Criteria andCreateOptidIn(List<String> values) {
            addCriterion("CREATE_OPTID in", values, "createOptid");
            return (Criteria) this;
        }

        public Criteria andCreateOptidNotIn(List<String> values) {
            addCriterion("CREATE_OPTID not in", values, "createOptid");
            return (Criteria) this;
        }

        public Criteria andCreateOptidBetween(String value1, String value2) {
            addCriterion("CREATE_OPTID between", value1, value2, "createOptid");
            return (Criteria) this;
        }

        public Criteria andCreateOptidNotBetween(String value1, String value2) {
            addCriterion("CREATE_OPTID not between", value1, value2, "createOptid");
            return (Criteria) this;
        }

        public Criteria andCreatDateIsNull() {
            addCriterion("CREAT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatDateIsNotNull() {
            addCriterion("CREAT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatDateEqualTo(Date value) {
            addCriterion("CREAT_DATE =", value, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateNotEqualTo(Date value) {
            addCriterion("CREAT_DATE <>", value, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateGreaterThan(Date value) {
            addCriterion("CREAT_DATE >", value, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREAT_DATE >=", value, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateLessThan(Date value) {
            addCriterion("CREAT_DATE <", value, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateLessThanOrEqualTo(Date value) {
            addCriterion("CREAT_DATE <=", value, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateIn(List<Date> values) {
            addCriterion("CREAT_DATE in", values, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateNotIn(List<Date> values) {
            addCriterion("CREAT_DATE not in", values, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateBetween(Date value1, Date value2) {
            addCriterion("CREAT_DATE between", value1, value2, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateNotBetween(Date value1, Date value2) {
            addCriterion("CREAT_DATE not between", value1, value2, "creatDate");
            return (Criteria) this;
        }

        public Criteria andBuildingTypeIsNull() {
            addCriterion("building_type is null");
            return (Criteria) this;
        }

        public Criteria andBuildingTypeIsNotNull() {
            addCriterion("building_type is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingTypeEqualTo(String value) {
            addCriterion("building_type =", value, "buildingType");
            return (Criteria) this;
        }

        public Criteria andBuildingTypeNotEqualTo(String value) {
            addCriterion("building_type <>", value, "buildingType");
            return (Criteria) this;
        }

        public Criteria andBuildingTypeGreaterThan(String value) {
            addCriterion("building_type >", value, "buildingType");
            return (Criteria) this;
        }

        public Criteria andBuildingTypeGreaterThanOrEqualTo(String value) {
            addCriterion("building_type >=", value, "buildingType");
            return (Criteria) this;
        }

        public Criteria andBuildingTypeLessThan(String value) {
            addCriterion("building_type <", value, "buildingType");
            return (Criteria) this;
        }

        public Criteria andBuildingTypeLessThanOrEqualTo(String value) {
            addCriterion("building_type <=", value, "buildingType");
            return (Criteria) this;
        }

        public Criteria andBuildingTypeLike(String value) {
            addCriterion("building_type like", value, "buildingType");
            return (Criteria) this;
        }

        public Criteria andBuildingTypeNotLike(String value) {
            addCriterion("building_type not like", value, "buildingType");
            return (Criteria) this;
        }

        public Criteria andBuildingTypeIn(List<String> values) {
            addCriterion("building_type in", values, "buildingType");
            return (Criteria) this;
        }

        public Criteria andBuildingTypeNotIn(List<String> values) {
            addCriterion("building_type not in", values, "buildingType");
            return (Criteria) this;
        }

        public Criteria andBuildingTypeBetween(String value1, String value2) {
            addCriterion("building_type between", value1, value2, "buildingType");
            return (Criteria) this;
        }

        public Criteria andBuildingTypeNotBetween(String value1, String value2) {
            addCriterion("building_type not between", value1, value2, "buildingType");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanyidIsNull() {
            addCriterion("PROPERTY_COMPANYId is null");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanyidIsNotNull() {
            addCriterion("PROPERTY_COMPANYId is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanyidEqualTo(String value) {
            addCriterion("PROPERTY_COMPANYId =", value, "propertyCompanyid");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanyidNotEqualTo(String value) {
            addCriterion("PROPERTY_COMPANYId <>", value, "propertyCompanyid");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanyidGreaterThan(String value) {
            addCriterion("PROPERTY_COMPANYId >", value, "propertyCompanyid");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanyidGreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTY_COMPANYId >=", value, "propertyCompanyid");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanyidLessThan(String value) {
            addCriterion("PROPERTY_COMPANYId <", value, "propertyCompanyid");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanyidLessThanOrEqualTo(String value) {
            addCriterion("PROPERTY_COMPANYId <=", value, "propertyCompanyid");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanyidLike(String value) {
            addCriterion("PROPERTY_COMPANYId like", value, "propertyCompanyid");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanyidNotLike(String value) {
            addCriterion("PROPERTY_COMPANYId not like", value, "propertyCompanyid");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanyidIn(List<String> values) {
            addCriterion("PROPERTY_COMPANYId in", values, "propertyCompanyid");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanyidNotIn(List<String> values) {
            addCriterion("PROPERTY_COMPANYId not in", values, "propertyCompanyid");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanyidBetween(String value1, String value2) {
            addCriterion("PROPERTY_COMPANYId between", value1, value2, "propertyCompanyid");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanyidNotBetween(String value1, String value2) {
            addCriterion("PROPERTY_COMPANYId not between", value1, value2, "propertyCompanyid");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanynameIsNull() {
            addCriterion("PROPERTY_COMPANYNAME is null");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanynameIsNotNull() {
            addCriterion("PROPERTY_COMPANYNAME is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanynameEqualTo(String value) {
            addCriterion("PROPERTY_COMPANYNAME =", value, "propertyCompanyname");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanynameNotEqualTo(String value) {
            addCriterion("PROPERTY_COMPANYNAME <>", value, "propertyCompanyname");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanynameGreaterThan(String value) {
            addCriterion("PROPERTY_COMPANYNAME >", value, "propertyCompanyname");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanynameGreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTY_COMPANYNAME >=", value, "propertyCompanyname");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanynameLessThan(String value) {
            addCriterion("PROPERTY_COMPANYNAME <", value, "propertyCompanyname");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanynameLessThanOrEqualTo(String value) {
            addCriterion("PROPERTY_COMPANYNAME <=", value, "propertyCompanyname");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanynameLike(String value) {
            addCriterion("PROPERTY_COMPANYNAME like", value, "propertyCompanyname");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanynameNotLike(String value) {
            addCriterion("PROPERTY_COMPANYNAME not like", value, "propertyCompanyname");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanynameIn(List<String> values) {
            addCriterion("PROPERTY_COMPANYNAME in", values, "propertyCompanyname");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanynameNotIn(List<String> values) {
            addCriterion("PROPERTY_COMPANYNAME not in", values, "propertyCompanyname");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanynameBetween(String value1, String value2) {
            addCriterion("PROPERTY_COMPANYNAME between", value1, value2, "propertyCompanyname");
            return (Criteria) this;
        }

        public Criteria andPropertyCompanynameNotBetween(String value1, String value2) {
            addCriterion("PROPERTY_COMPANYNAME not between", value1, value2, "propertyCompanyname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_bulidinglist_info
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 03 11:41:43 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_bulidinglist_info
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}