package com.sitech.cbn.cust.po;

import java.util.Date;

public class BsBulidinglistInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_bulidinglist_info.BUILDING_NO
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    private Long buildingNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_bulidinglist_info.TENANCY_CODE
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    private String tenancyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_bulidinglist_info.BUILDING_NAME
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    private String buildingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_bulidinglist_info.BUILDING_ADDR
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    private String buildingAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_bulidinglist_info.BUILDING_AGENT
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    private String buildingAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_bulidinglist_info.Building_AgentName
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    private String buildingAgentname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_bulidinglist_info.AM_ID
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    private String amId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_bulidinglist_info.OP_DATE
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    private Date opDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_bulidinglist_info.OP_OPTID
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    private String opOptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_bulidinglist_info.CREATE_OPTID
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    private String createOptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_bulidinglist_info.CREAT_DATE
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    private Date creatDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_bulidinglist_info.building_type
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    private String buildingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_bulidinglist_info.PROPERTY_COMPANYId
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    private String propertyCompanyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_bulidinglist_info.PROPERTY_COMPANYNAME
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    private String propertyCompanyname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_bulidinglist_info.BUILDING_NO
     *
     * @return the value of bs_bulidinglist_info.BUILDING_NO
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public Long getBuildingNo() {
        return buildingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_bulidinglist_info.BUILDING_NO
     *
     * @param buildingNo the value for bs_bulidinglist_info.BUILDING_NO
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void setBuildingNo(Long buildingNo) {
        this.buildingNo = buildingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_bulidinglist_info.TENANCY_CODE
     *
     * @return the value of bs_bulidinglist_info.TENANCY_CODE
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public String getTenancyCode() {
        return tenancyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_bulidinglist_info.TENANCY_CODE
     *
     * @param tenancyCode the value for bs_bulidinglist_info.TENANCY_CODE
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void setTenancyCode(String tenancyCode) {
        this.tenancyCode = tenancyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_bulidinglist_info.BUILDING_NAME
     *
     * @return the value of bs_bulidinglist_info.BUILDING_NAME
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_bulidinglist_info.BUILDING_NAME
     *
     * @param buildingName the value for bs_bulidinglist_info.BUILDING_NAME
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_bulidinglist_info.BUILDING_ADDR
     *
     * @return the value of bs_bulidinglist_info.BUILDING_ADDR
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public String getBuildingAddr() {
        return buildingAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_bulidinglist_info.BUILDING_ADDR
     *
     * @param buildingAddr the value for bs_bulidinglist_info.BUILDING_ADDR
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void setBuildingAddr(String buildingAddr) {
        this.buildingAddr = buildingAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_bulidinglist_info.BUILDING_AGENT
     *
     * @return the value of bs_bulidinglist_info.BUILDING_AGENT
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public String getBuildingAgent() {
        return buildingAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_bulidinglist_info.BUILDING_AGENT
     *
     * @param buildingAgent the value for bs_bulidinglist_info.BUILDING_AGENT
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void setBuildingAgent(String buildingAgent) {
        this.buildingAgent = buildingAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_bulidinglist_info.Building_AgentName
     *
     * @return the value of bs_bulidinglist_info.Building_AgentName
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public String getBuildingAgentname() {
        return buildingAgentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_bulidinglist_info.Building_AgentName
     *
     * @param buildingAgentname the value for bs_bulidinglist_info.Building_AgentName
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void setBuildingAgentname(String buildingAgentname) {
        this.buildingAgentname = buildingAgentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_bulidinglist_info.AM_ID
     *
     * @return the value of bs_bulidinglist_info.AM_ID
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public String getAmId() {
        return amId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_bulidinglist_info.AM_ID
     *
     * @param amId the value for bs_bulidinglist_info.AM_ID
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void setAmId(String amId) {
        this.amId = amId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_bulidinglist_info.OP_DATE
     *
     * @return the value of bs_bulidinglist_info.OP_DATE
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public Date getOpDate() {
        return opDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_bulidinglist_info.OP_DATE
     *
     * @param opDate the value for bs_bulidinglist_info.OP_DATE
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void setOpDate(Date opDate) {
        this.opDate = opDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_bulidinglist_info.OP_OPTID
     *
     * @return the value of bs_bulidinglist_info.OP_OPTID
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public String getOpOptid() {
        return opOptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_bulidinglist_info.OP_OPTID
     *
     * @param opOptid the value for bs_bulidinglist_info.OP_OPTID
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void setOpOptid(String opOptid) {
        this.opOptid = opOptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_bulidinglist_info.CREATE_OPTID
     *
     * @return the value of bs_bulidinglist_info.CREATE_OPTID
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public String getCreateOptid() {
        return createOptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_bulidinglist_info.CREATE_OPTID
     *
     * @param createOptid the value for bs_bulidinglist_info.CREATE_OPTID
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void setCreateOptid(String createOptid) {
        this.createOptid = createOptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_bulidinglist_info.CREAT_DATE
     *
     * @return the value of bs_bulidinglist_info.CREAT_DATE
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public Date getCreatDate() {
        return creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_bulidinglist_info.CREAT_DATE
     *
     * @param creatDate the value for bs_bulidinglist_info.CREAT_DATE
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void setCreatDate(Date creatDate) {
        this.creatDate = creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_bulidinglist_info.building_type
     *
     * @return the value of bs_bulidinglist_info.building_type
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public String getBuildingType() {
        return buildingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_bulidinglist_info.building_type
     *
     * @param buildingType the value for bs_bulidinglist_info.building_type
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void setBuildingType(String buildingType) {
        this.buildingType = buildingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_bulidinglist_info.PROPERTY_COMPANYId
     *
     * @return the value of bs_bulidinglist_info.PROPERTY_COMPANYId
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public String getPropertyCompanyid() {
        return propertyCompanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_bulidinglist_info.PROPERTY_COMPANYId
     *
     * @param propertyCompanyid the value for bs_bulidinglist_info.PROPERTY_COMPANYId
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void setPropertyCompanyid(String propertyCompanyid) {
        this.propertyCompanyid = propertyCompanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_bulidinglist_info.PROPERTY_COMPANYNAME
     *
     * @return the value of bs_bulidinglist_info.PROPERTY_COMPANYNAME
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public String getPropertyCompanyname() {
        return propertyCompanyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_bulidinglist_info.PROPERTY_COMPANYNAME
     *
     * @param propertyCompanyname the value for bs_bulidinglist_info.PROPERTY_COMPANYNAME
     *
     * @mbg.generated Thu Sep 03 11:41:43 CST 2020
     */
    public void setPropertyCompanyname(String propertyCompanyname) {
        this.propertyCompanyname = propertyCompanyname;
    }
}